### ISSUE TITLE
"Product Bundles" missing from navigation.

### ISSUE THREAD

**Issue by zachshallbetter** [onyourmarks-agency/craft-commerce-product-bundles#6]
When installing the plugin on Craft 3.4.19 with Commerce 3.1.3, "Product Bundles" does not appear as a subnav link below Commerce within the control panel. I can navigate to _/commerce-product-bundles/bundles/index_ but it does provide a button to create a bundle.

I verified the vendor directory permissions and ownership, reinstalled the plugin without luck, and updated composer. There were not any logged events.
 
<img width="218" alt="Screen Shot 2020-05-13 at 4 33 16 PM" src="https://user-images.githubusercontent.com/949434/81876470-a576fd00-9537-11ea-9ebf-2cb032840c51.png">
<img width="1321" alt="Screen Shot 2020-05-13 at 4 37 33 PM" src="https://user-images.githubusercontent.com/949434/81876780-554c6a80-9538-11ea-9490-d03d276d9426.png">

**Comment by jerome2710** [comment]
Hi @zachshallbetter,

Thank you for sharing this issue and providing us with version information and screenshots. This helps tracking down the issue and fixing it sooner.

I have just made some adjustments and released v1.1.1, which should solve this issue!
